import { NextResponse } from 'next/server';
import { db } from '@/lib/firebase';
import { collection, query, where, getDocs, updateDoc, deleteDoc } from 'firebase/firestore';
import { revalidatePath } from 'next/cache';

export async function PUT(req, { params }) {
  try {
    const { id } = await params;
    const updatedData = await req.json();

    const q = query(collection(db, 'articles'), where('id', '==', parseInt(id)));
    const snapshot = await getDocs(q);

    if (snapshot.empty) {
      return NextResponse.json({ error: 'Article not found' }, { status: 404 });
    }

    const docRef = snapshot.docs[0].ref;
    
    // Ensure content is parsed back to an array/object if it was stringified from the frontend textarea
    let parsedContent = updatedData.content;
    if (typeof parsedContent === 'string') {
      try {
        parsedContent = JSON.parse(parsedContent);
      } catch (e) {
        // Keep as string if it's not valid JSON (e.g. markdown/html generated by AI)
      }
    }

    const dataToUpdate = { ...updatedData, content: parsedContent };
    
    await updateDoc(docRef, dataToUpdate);

    revalidatePath('/guide');
    revalidatePath('/admin');

    return NextResponse.json({ success: true, ...dataToUpdate });
  } catch (error) {
    console.error('Error updating article:', error);
    return NextResponse.json({ error: 'Failed to update article' }, { status: 500 });
  }
}

export async function DELETE(req, { params }) {
  try {
    const { id } = await params;
    
    const q = query(collection(db, 'articles'), where('id', '==', parseInt(id)));
    const snapshot = await getDocs(q);
    
    if (!snapshot.empty) {
      await deleteDoc(snapshot.docs[0].ref);
    }
    
    revalidatePath('/guide');
    revalidatePath('/admin');
    
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting article:', error);
    return NextResponse.json({ error: 'Failed to delete article' }, { status: 500 });
  }
}
