// 가효상조 Mock 데이터베이스
// 실제 DB(PostgreSQL 등) 연결 전 프론트엔드 선행 개발용

export const funeralHalls = [
  {
    id: 1,
    name: "서울 삼성 장례식장",
    regionCode: "seoul",
    address: "서울특별시 강남구 일원로 81",
    contact: "02-3410-2000",
    rating: 4.8,
    reviewCount: 124,
    thumbnail: null,
    images: [],
    latitude: 37.488421,
    longitude: 127.086716,
    facilityInfo: {
      sliderEnabled: true,
      descriptionEnabled: true,
      description: "최첨단 시설을 갖춘 서울 강남권 대표 장례식장으로, 넓은 주차 공간과 다양한 규모의 빈소를 제공합니다. 숙련된 전문 인력이 24시간 상주하여 유가족의 슬픔을 함께합니다.",
      pricingEnabled: true,
      mapEnabled: true,
      consultEnabled: true,
      parkingInfo: "지하 3층 주차장 (최대 350대)",
      visitorsCapacity: "최대 500명",
      hallCount: 12,
    },
    pricingData: [
      { item: "소형 빈소 (50인 이하)", price: "1,500,000" },
      { item: "중형 빈소 (100인 이하)", price: "2,500,000" },
      { item: "대형 빈소 (200인 이상)", price: "4,200,000" },
      { item: "식사 (1인당)", price: "15,000" },
    ],
    moduleOrder: ["slider", "description", "pricing", "map", "consult"],
    features: ["24시간 운영", "주차 가능", "식사 제공", "장례지도사 상주"],
  },
  {
    id: 2,
    name: "경기 수원 한국 장례식장",
    regionCode: "gyeonggi",
    address: "경기도 수원시 영통구 광교로 164",
    contact: "031-210-7777",
    rating: 4.6,
    reviewCount: 89,
    thumbnail: null,
    images: [],
    latitude: 37.291112,
    longitude: 127.051696,
    facilityInfo: {
      sliderEnabled: true,
      descriptionEnabled: true,
      description: "경기 남부권 최대 규모의 장례식장으로, 모든 종교적 의식을 수용할 수 있는 다목적 빈소를 보유하고 있습니다. 가족 휴게실과 샤워 시설을 완비하여 편안한 장례를 돕습니다.",
      pricingEnabled: true,
      mapEnabled: true,
      consultEnabled: true,
      parkingInfo: "지상/지하 주차장 (최대 200대)",
      visitorsCapacity: "최대 300명",
      hallCount: 8,
    },
    pricingData: [
      { item: "소형 빈소 (50인 이하)", price: "1,200,000" },
      { item: "중형 빈소 (100인 이하)", price: "2,000,000" },
      { item: "대형 빈소 (200인 이상)", price: "3,500,000" },
      { item: "식사 (1인당)", price: "13,000" },
    ],
    moduleOrder: ["slider", "description", "pricing", "map", "consult"],
    features: ["24시간 운영", "주차 가능", "식사 제공", "종교 의식 가능"],
  },
  {
    id: 3,
    name: "인천 가톨릭 의료원 장례식장",
    regionCode: "incheon",
    address: "인천광역시 남동구 인주대로 665",
    contact: "032-240-5800",
    rating: 4.7,
    reviewCount: 67,
    thumbnail: null,
    images: [],
    latitude: 37.456432,
    longitude: 126.735012,
    facilityInfo: {
      sliderEnabled: true,
      descriptionEnabled: true,
      description: "인천 가톨릭 의료원 부속 장례식장으로, 종교적 전통을 존중하는 섬세한 장례 서비스를 제공합니다. 병원 연계로 편리한 임종 후 절차 진행이 가능합니다.",
      pricingEnabled: true,
      mapEnabled: true,
      consultEnabled: true,
      parkingInfo: "병원 공용 주차장 이용",
      visitorsCapacity: "최대 200명",
      hallCount: 6,
    },
    pricingData: [
      { item: "소형 빈소 (50인 이하)", price: "1,300,000" },
      { item: "중형 빈소 (100인 이하)", price: "2,200,000" },
      { item: "대형 빈소 (150인 이상)", price: "3,800,000" },
      { item: "식사 (1인당)", price: "14,000" },
    ],
    moduleOrder: ["slider", "description", "pricing", "map", "consult"],
    features: ["가톨릭 의식", "병원 연계", "24시간 운영", "주차 가능"],
  },
  {
    id: 4,
    name: "대전 을지 장례식장",
    regionCode: "daejeon",
    address: "대전광역시 서구 둔산서로 95",
    contact: "042-611-3000",
    rating: 4.5,
    reviewCount: 55,
    thumbnail: null,
    images: [],
    latitude: 36.350401,
    longitude: 127.384900,
    facilityInfo: {
      sliderEnabled: true,
      descriptionEnabled: true,
      description: "대전 서구의 중심에 위치한 을지 장례식장은 편리한 교통과 넓은 편의시설을 자랑합니다. 충청권 전역에서 쉽게 방문 가능하며, 전통 및 현대식 장례 서비스를 모두 지원합니다.",
      pricingEnabled: true,
      mapEnabled: true,
      consultEnabled: true,
      parkingInfo: "전용 주차장 (최대 150대)",
      visitorsCapacity: "최대 250명",
      hallCount: 7,
    },
    pricingData: [
      { item: "소형 빈소 (50인 이하)", price: "1,100,000" },
      { item: "중형 빈소 (100인 이하)", price: "1,900,000" },
      { item: "대형 빈소 (200인 이상)", price: "3,200,000" },
      { item: "식사 (1인당)", price: "12,000" },
    ],
    moduleOrder: ["slider", "description", "pricing", "map", "consult"],
    features: ["편리한 교통", "24시간 운영", "식사 제공", "전통/현대 겸비"],
  },
  {
    id: 5,
    name: "대구 계명대 동산 장례식장",
    regionCode: "daegu",
    address: "대구광역시 달서구 달구벌대로 1035",
    contact: "053-250-7114",
    rating: 4.9,
    reviewCount: 98,
    thumbnail: null,
    images: [],
    latitude: 35.872296,
    longitude: 128.531822,
    facilityInfo: {
      sliderEnabled: true,
      descriptionEnabled: true,
      description: "계명대학교 의과대학 부속 동산병원 내에 위치한 장례식장으로, 최신 시설과 전문 인력이 자랑입니다. 대구·경북 지역 최고 수준의 서비스를 제공합니다.",
      pricingEnabled: true,
      mapEnabled: true,
      consultEnabled: true,
      parkingInfo: "병원 주차타워 (최대 500대)",
      visitorsCapacity: "최대 400명",
      hallCount: 10,
    },
    pricingData: [
      { item: "소형 빈소 (50인 이하)", price: "1,400,000" },
      { item: "중형 빈소 (100인 이하)", price: "2,300,000" },
      { item: "대형 빈소 (200인 이상)", price: "4,000,000" },
      { item: "식사 (1인당)", price: "14,000" },
    ],
    moduleOrder: ["slider", "description", "pricing", "map", "consult"],
    features: ["병원 연계", "24시간 운영", "대용량 주차", "전문 지도사"],
  },
  {
    id: 6,
    name: "광주 전남대학교병원 장례식장",
    regionCode: "gwangju",
    address: "광주광역시 동구 제봉로 42",
    contact: "062-220-5114",
    rating: 4.6,
    reviewCount: 73,
    thumbnail: null,
    images: [],
    latitude: 35.148439,
    longitude: 126.921734,
    facilityInfo: {
      sliderEnabled: true,
      descriptionEnabled: true,
      description: "전남대학교병원 내에 위치한 장례식장으로 호남권 최대 규모를 자랑합니다. 깔끔한 시설과 친절한 서비스로 유가족의 슬픔을 함께합니다.",
      pricingEnabled: true,
      mapEnabled: true,
      consultEnabled: true,
      parkingInfo: "병원 부설 주차장 이용",
      visitorsCapacity: "최대 350명",
      hallCount: 9,
    },
    pricingData: [
      { item: "소형 빈소 (50인 이하)", price: "1,200,000" },
      { item: "중형 빈소 (100인 이하)", price: "2,100,000" },
      { item: "대형 빈소 (200인 이상)", price: "3,600,000" },
      { item: "식사 (1인당)", price: "13,000" },
    ],
    moduleOrder: ["slider", "description", "pricing", "map", "consult"],
    features: ["병원 연계", "24시간 운영", "식사 제공", "호남권 최대"],
  },
];

export const cemeteries = [
  {
    id: 1,
    name: "하늘숲 자연장지",
    regionCode: "gyeonggi",
    address: "경기도 가평군 설악면 선촌리 산 1",
    contact: "031-585-1234",
    type: "수목장",
    typeLabel: "자연장지",
    description: "자연 속에서 편안히 잠드는 친환경 수목장지입니다. 사계절 아름다운 숲속에서 가족들이 편안히 방문할 수 있습니다.",
    benefits: ["가효상조 고객 10% 할인", "전용 주차 공간 제공", "연간 1회 무료 벌초 서비스"],
    priceRange: "150만원 ~ 400만원",
    thumbnail: null,
  },
  {
    id: 2,
    name: "서울 추모공원 봉안당",
    regionCode: "seoul",
    address: "서울특별시 서초구 헌릉로 562",
    contact: "02-459-7700",
    type: "봉안당",
    typeLabel: "봉안시설",
    description: "서울 시내에 위치한 현대식 봉안당으로, 사계절 방문이 용이하며 쾌적하고 품격 있는 시설을 갖추고 있습니다.",
    benefits: ["가효상조 고객 15% 할인", "교통 편의 제공", "연중무휴 관리"],
    priceRange: "200만원 ~ 600만원",
    thumbnail: null,
  },
  {
    id: 3,
    name: "청풍 자연공원묘지",
    regionCode: "chungbuk",
    address: "충청북도 제천시 청풍면 능강리 산 17",
    contact: "043-647-3000",
    type: "평장",
    typeLabel: "묘지",
    description: "청풍호가 내려다보이는 아름다운 자연경관 속 평장묘지입니다. 넓은 부지와 쾌적한 환경이 특징입니다.",
    benefits: ["가효상조 고객 20% 할인", "연 2회 무료 관리 서비스"],
    priceRange: "300만원 ~ 800만원",
    thumbnail: null,
  },
  {
    id: 4,
    name: "부산 추모의 집",
    regionCode: "busan",
    address: "부산광역시 기장군 철마면 구칭리 산 26",
    contact: "051-727-5000",
    type: "봉안당",
    typeLabel: "봉안시설",
    description: "부산·경남권 최대 규모의 복합 봉안당으로, 최신 시설과 함께 편안한 추모 공간을 제공합니다.",
    benefits: ["가효상조 고객 12% 할인", "전용 셔틀버스 운행", "온라인 추모관 무료 개설"],
    priceRange: "180만원 ~ 500만원",
    thumbnail: null,
  },
  {
    id: 5,
    name: "제주 한라수목장",
    regionCode: "jeju",
    address: "제주특별자치도 제주시 조천읍 산굼부리로 168",
    contact: "064-783-2000",
    type: "수목장",
    typeLabel: "자연장지",
    description: "제주의 청정 자연 속에서 영원한 안식을 취할 수 있는 수목장지로, 사계절 아름다운 경치가 유가족에게 위안이 됩니다.",
    benefits: ["가효상조 고객 10% 할인", "항공편 연계 서비스", "연간 2회 관리 서비스"],
    priceRange: "200만원 ~ 500만원",
    thumbnail: null,
  },
];

export const guideArticles = [
  {
    id: 1,
    title: "임종 후 첫 24시간, 무엇을 해야 할까?",
    summary: "갑작스러운 임종 후 가족들이 당황하지 않도록 꼭 알아야 할 첫 24시간 행동 지침을 안내합니다.",
    category: "임종절차",
    readTime: "5분",
    thumbnail: null,
    publishedAt: "2025-01-15",
    content: [
      { step: 1, title: "의사 또는 119에 연락", description: "임종 확인을 위해 병원 주치의 또는 119에 즉시 연락하세요. 사망진단서 발급이 필요합니다." },
      { step: 2, title: "장례식장 결정", description: "장례를 치를 장례식장을 선정합니다. 가효상조에 연락하시면 전국 장례식장 정보를 바탕으로 최적의 선택을 도와드립니다." },
      { step: 3, title: "부고 알리기", description: "가까운 친척과 지인에게 부고를 전달합니다. 부고 문자 형식이 필요하시면 가이드를 참조하세요." },
    ],
  },
  {
    id: 2,
    title: "부고 문자 보내는 법 (예시 포함)",
    summary: "슬픈 소식을 전하는 부고 문자, 실례 포함 상황별 올바른 작성법을 알려드립니다.",
    category: "행정절차",
    readTime: "3분",
    thumbnail: null,
    publishedAt: "2025-01-20",
    content: [],
  },
  {
    id: 3,
    title: "장례 비용, 얼마나 들까? 투명한 비용 가이드",
    summary: "장례식 평균 비용부터 항목별 세부 내역까지, 숨겨진 비용 없이 투명하게 알려드립니다.",
    category: "비용안내",
    readTime: "7분",
    thumbnail: null,
    publishedAt: "2025-02-01",
    content: [],
  },
  {
    id: 4,
    title: "수목장 vs 봉안당 vs 평장, 나에게 맞는 장지 선택법",
    summary: "다양한 장묘 형태의 특징과 장단점을 비교하여 유가족이 올바른 선택을 할 수 있도록 돕습니다.",
    category: "장지정보",
    readTime: "6분",
    thumbnail: null,
    publishedAt: "2025-02-10",
    content: [],
  },
  {
    id: 5,
    title: "사망신고 절차 완벽 가이드 (행정 서류 총정리)",
    summary: "사망 후 7일 이내 처리해야 하는 사망신고, 준비 서류와 신고 방법을 단계별로 정리했습니다.",
    category: "행정절차",
    readTime: "5분",
    thumbnail: null,
    publishedAt: "2025-02-20",
    content: [],
  },
  {
    id: 6,
    title: "종교별 장례 의식 이해하기 (불교·기독교·천주교·무교)",
    summary: "각 종교의 장례 의식 절차와 주의사항을 정리하여 조문 시 실수하지 않도록 도와드립니다.",
    category: "장례문화",
    readTime: "8분",
    thumbnail: null,
    publishedAt: "2025-03-05",
    content: [],
  },
];

// 지역별 기본 장례 비용 데이터 (AI 견적 계산용)
export const regionPricing = {
  seoul:    { baseFee: 3000000, label: "서울" },
  gyeonggi: { baseFee: 2500000, label: "경기" },
  incheon:  { baseFee: 2400000, label: "인천" },
  gangwon:  { baseFee: 2000000, label: "강원" },
  chungbuk: { baseFee: 1900000, label: "충북" },
  chungnam: { baseFee: 1900000, label: "충남" },
  daejeon:  { baseFee: 2100000, label: "대전" },
  jeonbuk:  { baseFee: 1800000, label: "전북" },
  jeonnam:  { baseFee: 1800000, label: "전남" },
  gwangju:  { baseFee: 2000000, label: "광주" },
  gyeongbuk:{ baseFee: 1900000, label: "경북" },
  gyeongnam:{ baseFee: 2000000, label: "경남" },
  daegu:    { baseFee: 2200000, label: "대구" },
  busan:    { baseFee: 2300000, label: "부산" },
  ulsan:    { baseFee: 2100000, label: "울산" },
  jeju:     { baseFee: 2200000, label: "제주" },
};

// 견적 계산 함수
export function calculateEstimate({ region, guestCount, options }) {
  const base = regionPricing[region]?.baseFee || 2000000;
  const mealCost = guestCount * 15000;
  const hallSizeFee = guestCount > 200 ? 1500000 : guestCount > 100 ? 800000 : 0;

  let optionsFee = 0;
  if (options.includes("flower")) optionsFee += 500000;
  if (options.includes("premium_shroud")) optionsFee += 800000;
  if (options.includes("video_tribute")) optionsFee += 300000;
  if (options.includes("limousine")) optionsFee += 600000;

  const subtotal = base + mealCost + hallSizeFee + optionsFee;
  const min = Math.round(subtotal * 0.9 / 10000) * 10000;
  const max = Math.round(subtotal * 1.1 / 10000) * 10000;

  return {
    min,
    max,
    breakdown: {
      baseFee: base,
      mealCost,
      hallSizeFee,
      optionsFee,
    },
  };
}

export const regions = Object.entries(regionPricing).map(([code, data]) => ({
  code,
  label: data.label,
}));

export const estimateOptions = [
  { id: "flower", label: "프리미엄 제단 꽃 장식", price: 500000, description: "고급 생화로 구성된 프리미엄 제단 꽃 장식" },
  { id: "premium_shroud", label: "명품 수의", price: 800000, description: "고급 천연 소재의 명품 수의" },
  { id: "video_tribute", label: "추모 영상 제작", price: 300000, description: "고인의 사진으로 만드는 감동적인 추모 영상" },
  { id: "limousine", label: "운구 리무진 서비스", price: 600000, description: "격식 있는 운구를 위한 전용 리무진 서비스" },
];
